In [22]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [29]:
from dotenv import load_dotenv

load_dotenv()

True

In [95]:
import pandas as pd

mags = pd.read_csv("C:/Users/juniu/PycharmProjects/SubFinda/final_mags.csv")

In [102]:
import csv
import re

mags["tagged_description"] = mags["tagged_description"].fillna("").str.replace('"', '', regex=False)

mags["tagged_description"].to_csv(
    "tagged_description.txt",
    index=False,
    header=False,
    quoting=csv.QUOTE_MINIMAL,
    escapechar="\\"
)

In [103]:
mags["tagged_description"]

0     0001McSweeney?s is a nonprofit publishing comp...
1     0002At The Yale Review, we believe in the powe...
2     0003This magazine aims to merge the worlds of ...
3     0004Taco Bell Quarterly seeks literary/creativ...
4     0005We welcome all types of poetry (including,...
5     0006The Acentos Review shoots from the spring ...
6     0007Aethlon: The Journal of Sport Literature i...
7     0008DIAGRAM is an online literary magazine fou...
8     0009We accept everything. Text-based. Visual. ...
9     0010We are on the lookout for contemporary lit...
10    0011Action, Spectacle welcomes submissions via...
11    0012We appreciate good writing in any genre. W...
12    0013?Agapanthus? Amaryllidaceae agapanthus Fro...
13    0014Our literary journal, ionosphere, focuses ...
14    0015Simply put, Across the Margin is an online...
15    0016We take our name from the dotted line on a...
16    0017One day in the summer of 2013, three frien...
17    0018AURORE is real, non-fiction erotica, writt...
18    0019Based in Belfast, Northern Ireland, we are...
19    0020African Writer Magazine is a New Jersey-ba...
20    0021We aim to publish poetry that adds value t...
21    0022It is the editors? belief that American li...
22    0023Muzzle Magazine is an online literary maga...
23    0024The CryptoNaturalist podcast is a scripted...
24    0025The Belladonna is a comedy and satire site...
25    0026Messy Misfits Club zine is looking for sto...
26    0027The South Carolina Review is reimagining t...
27    0028Mission\nOur longstanding mission is to se...
28    0029Snowflake magazine is looking for submissi...
29    0030Humana Obscura is an independent literary ...
30    0031ANMLY is committed to actively seeking out...
31    0032The magazine was founded in 1889 by studen...
32    0033Founded in 1986, Hayden?s Ferry Review is ...
33    0034Friends Publishing Corporation was founded...
34    0035Boston Review is a political and literary ...
35    0036Apex Magazine is an online zine of fantast...
36    0037For over a decade, PseudoPod has been brin...
37    0038The B?K is a quarterly art and lit, online...
38    0039For many years, The Puritan represented bo...
39    0040The Good Life Review is an independently o...
40    0041Umbrella Factory Magazine is a small press...
41    0042Torch Literary Arts started as a passion p...
42    0043Toronto Journal is a writing journal in pr...
43    0044Pictura Journal seeks work that offers a v...
44    0045As an online press for dark literature, we...
45    0046Landfall contains literary fiction and ess...
46    0047Landfall contains literary fiction and ess...
47
48
49
Name: tagged_description, dtype: object

In [104]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 1480, which is longer than the specified 0
Created a chunk of size 783, which is longer than the specified 0
Created a chunk of size 848, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 1051, which is longer than the specified 0
Created a chunk of size 334, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 132, which is longer than the specified 0
Created a chunk of size 609, which is longer than the specified 0
Created a chunk of size 542, which is longer than the specified 0
Created a chunk of size 991, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 366, which is longer than the specified 0
Created a chunk of size 313, which is longer than the specified 0
Created a chunk of size 999, which is longer than the specified 0
Created a chunk of size 634, which is longer than the specified 0
Created a chunk of size 174, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 358, which is longer than the specified 0
Created a chunk of size 568, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 660, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 162, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 689, which is longer than the specified 0
Created a chunk of size 333, which is longer than the specified 0
Created a chunk of size 667, which is longer than the specified 0
Created a chunk of size 966, which is longer than the specified 0
Created a chunk of size 11, which is longer than the specified 0
Created a chunk of size 431, which is longer than the specified 0
Created a chunk of size 1486, which is longer than the specified 0
Created a chunk of size 469, which is longer than the specified 0
Created a chunk of size 724, which is longer than the specified 0
Created a chunk of size 679, which is longer than the specified 0
Created a chunk of size 855, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 605, which is longer than the specified 0
Created a chunk of size 978, which is longer than the specified 0
Created a chunk of size 549, which is longer than the specified 0
Created a chunk of size 924, which is longer than the specified 0
Created a chunk of size 134, which is longer than the specified 0
Created a chunk of size 747, which is longer than the specified 0
Created a chunk of size 538, which is longer than the specified 0
Created a chunk of size 369, which is longer than the specified 0
Created a chunk of size 699, which is longer than the specified 0
Created a chunk of size 995, which is longer than the specified 0
Created a chunk of size 157, which is longer than the specified 0
Created a chunk of size 468, which is longer than the specified 0
Created a chunk of size 433, which is longer than the specified 0

In [106]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='0001McSweeney?s is a nonprofit publishing company based in San Francisco. As well as operating a daily humor website, we also publish Timothy McSweeney?s Quarterly Concern, Illustoria Magazine, and an ever-growing selection of books under various imprints. You can buy all of these things from our online store. You can support us today by making a donation.McSweeney?s exists to champion ambitious and inspired new writing, and to challenge conventional expectations about where it?s found, how it looks, and who participates.We?re here to discover things we love, help them find their most resplendent form, and imagine new ways to bring them to you, Dennis. (If you are not Dennis, kindly ignore the aforementioned.')

In [32]:
db_mags = Chroma.from_documents(
                    documents,
                   embedding=OpenAIEmbeddings())

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

In [34]:
query = "a magazine to submit horror stories to"
docs = db_mags.similarity_search(query, k = 10)
docs

[Document(id='3192f816-28fc-4cb3-9501-7993ac44f3ec', metadata={'source': 'tagged_description.txt'}, page_content='"315 Year round we are accepting short stories, preferably horror, speculative, or gothic in nature, though deviations to the genre can sometimes be acceptable. The magazine is of course mainly horror based so gore to some degree is permitted, however stories with an overabundance of erotic material or sadism are not allowed. Shock value fiction will only be considered if it is inherently clever."'),
 Document(id='611da64a-cedb-454e-9898-8894c175800d', metadata={'source': 'tagged_description.txt'}, page_content='214 Submissions should fit with the general theme of the magazine (Anything within the sphere of horror / weird fiction)'),
 Document(id='96154ab2-c554-46dd-ba83-366244bc028f', metadata={'source': 'tagged_description.txt'}, page_content='"403 If you think you’ve got what it takes to terrify, scar and haunt our audience of 150k+ monthly listeners, then we want your stories!"'),
 Document(id='2167e676-f13c-43ef-bc48-86da518fb57d', metadata={'source': 'tagged_description.txt'}, page_content='"82 We invite writers to submit their best speculative fiction stories for an upcoming anthology inspired by the master of macabre, Edgar Allan Poe. We’re seeking tales that capture the essence of Poe’s work—be it eerie atmospheres, twisted psychological depths, or hauntingly gothic settings—while adding your own speculative twist. Whether infused with science fiction, fantasy, horror, or an unexpected blend of genres, your stories should explore the dark and the mysterious through new lenses. Let your imagination run wild and honor Poe’s legacy with chilling tales that resonate with his timeless themes."'),
 Document(id='10b80d21-281b-4ab5-95fd-e08387c3bc97', metadata={'source': 'tagged_description.txt'}, page_content='"179 We are currently accepting submissions in the following genres: Fiction Horror Romance Fantasy Sci-Fi We are particularly interested in stories with strong characters, unique worlds, and compelling narratives. Whether you’re a debut author or an experienced writer, we’d love to hear from you!"'),
 Document(id='82a77f89-5756-402f-b4d5-641075824960', metadata={'source': 'tagged_description.txt'}, page_content='"359 Note: one submission per month We\'re on the hunt for tiny tales and impactful poems.  We welcome a broad range of genres, from contemporary to speculative fiction."'),
 Document(id='f1719d72-da79-49ac-bea1-1e21418bf4cb', metadata={'source': 'tagged_description.txt'}, page_content='"483 We publish speculative fiction: horror, dark scifi and fantasy, and more. If it’s dark and speculative, we’d love to read it."'),
 Document(id='23b3cda8-cba8-455e-bd3b-6e8154ac5868', metadata={'source': 'tagged_description.txt'}, page_content='"249 We are looking for good stories independent of genre or style, but we have a soft spot for dark fantasy, sci-fi, mystery, horror and humor. If you have a story that mixes some of these genres, even better! If you think your story is a misfit for most markets, send it to us."'),
 Document(id='0d0e59bf-f362-49ce-b156-c9bb493a9deb', metadata={'source': 'tagged_description.txt'}, page_content='"496 Note: we have received several reports of issues receiving finalized contracts, either publishing before any contract is received or difficulty receiving a countersigned contract. Note: after receiving a response, wait one month to submit again. SCI-FI & FANTASY Uncharted Magazine publishes Science Fiction/Fantasy Short Stories from fiction writers of any background or experience. We want stories that richly imagine the future of technology and science, that explore our world through a speculative lens. We want stories of fantasy that make us hunger for new worlds, new biomes, new places we can explore through thrilling sensual details and human empathy. We want stories that thrill us, that make us feel alive, that awaken our desires to explore and go on adventures. HORROR & THRILLER Uncharted Magazine publishes Horror/Thriller Short Stories from fiction writers of any background or experience. We want stories that keep us up at night, afraid to turn the corner. Stories that take us into the resonant fear of looming monsters and haunting ghosts. We want stories that thrill us by keeping us on the edges of our seats, hearts pounding, wondering how it will end! Stories with characters who refuse to stay in the shadows! We want stories that thrill us, that make us feel alive, that awaken our desires to explore and go on adventures.  CRIME & MYSTERY Uncharted Magazine publishes Crime/Mystery Short Stories from fiction writers of any background or experience. We want stories that delve into the psychology of crime, that explore desperate and dastardly characters committing crimes of passion and intrigue. We want stories of mystery that make us search for answers, for reasons, for the things that happen in the shadows. We want stories that thrill us, that make us feel alive, that awaken our desires to explore and go on adventures."'),
 Document(id='e53574ae-a53f-4d17-9393-7a7f99926ce5', metadata={'source': 'tagged_description.txt'}, page_content='"465 Timber Ghost Press is looking to publish high-quality ?horror fiction to include cosmic horror, weird horror, dark fantasy, sci-fi/horror, gothic, and contemporary. We especially love Old West mixed with horror.  We are currently looking for novels and novellas that fall into the following horror categories:     Hauntings     Possession     Cosmic Horror     Weird Horror     Sci-Fi/Horror     Old West/Horror     Gothic Horror"')]

In [37]:
mags[mags["row_number"] == int(docs[0].page_content.split()[0].strip('"'))]

,market_name,genres,lengths,response_time,description,row_number,tagged_description
279,The Canadian Sepulchral - Fiction,"Fantasy, Horror, Science Fiction",Short Story,13 days,"Year round we are accepting short stories, pre...",315,"315 Year round we are accepting short stories,..."

In [89]:
def retrieve_semantic_recommendations(query, top_k=16):
    recs = db_mags.similarity_search(query, k=top_k)


    mags_list = []

    for doc in recs:
        content = doc.page_content.strip()
        first_word = content.split()[0].replace('"', '')

        if first_word.isdigit():
            mags_list.append(int(first_word))


    return mags[mags["row_number"].isin(mags_list)].head(top_k)

In [71]:
mags["tagged_description"].to_csv("tagged_description.txt", index=False, header=False)

In [90]:
retrieve_semantic_recommendations("a magazine to stories of fantasy to")

,market_name,genres,lengths,response_time,description,row_number,tagged_description
2,Harvey Duckman Presents...,"Fantasy, Horror, Science Fiction, Young Adult","Short Story, Flash",100 days,"Sixth Element Publishing is looking for new, o...",3,"3 Sixth Element Publishing is looking for new,..."
32,Leading Edge - Fiction,"Fantasy, Science Fiction","Short Story, Novelette",255 days,Leading Edge is a science-fiction and fantasy ...,35,35 Leading Edge is a science-fiction and fanta...
87,Micromance - Fiction,Romance,"Flash, Short Story",32 days,"This is a magazine for romance stories, but pl...",97,"97 This is a magazine for romance stories, but..."
100,MoonLit Getaway - Fiction,General,"Flash, Short Story",40 days,Our content aims to enrapture readers with exc...,111,111 Our content aims to enrapture readers with...
105,Mystic Mind Magazine,"Action/Adventure, Fantasy, Science Fiction","Flash, Short Story",6 days,Mystic Mind Magazine is a Science Fiction + Fa...,116,116 Mystic Mind Magazine is a Science Fiction ...
123,NewMyths.com - Fiction,"Fantasy, Science Fiction, Humor","Flash, Short Story, Novelette",44 days,"At NewMyths Magazine, we like to balance each ...",135,"135 At NewMyths Magazine, we like to balance e..."
124,NewMyths.com - Poetry,"Fantasy, Science Fiction, Humor",Poetry,25 days,"At NewMyths Magazine, we like to balance each ...",137,"137 At NewMyths Magazine, we like to balance e..."
144,Orion's Beau - Fiction,"Fantasy, Horror, Science Fiction","Flash, Short Story",119 days,Thank you for your interest in submitting work...,159,159 Thank you for your interest in submitting ...
174,Piker Press - Fiction,"General, Horror, Science Fiction, Literary","Flash, Short Story, Novelette",12 days,The Press seeks an active balance between genr...,193,193 The Press seeks an active balance between ...
177,Pink Hydra Press - Fiction,"Erotica, Fantasy, Horror, Romance, Science Fic...","Novelette, Novella",18 days,"Genre-wise, we are looking for anything that f...",196,"196 Genre-wise, we are looking for anything th..."
326,The Kismet Magazine - Fiction,"Fantasy, Horror, Science Fiction","Flash, Short Story, Novelette",74 days,The Kismet Magazine is for those of us who mus...,367,367 The Kismet Magazine is for those of us who...
378,The Sprawl Mag - Fiction,"Fantasy, Science Fiction","Flash, Short Story",109 days,"The Sprawl Mag is a (cyber-)feminist, anti-col...",429,"429 The Sprawl Mag is a (cyber-)feminist, anti..."
379,The Sprawl Mag - Poetry,"Fantasy, Science Fiction",Poetry,104 days,"The Sprawl Mag is a (cyber-)feminist, anti-col...",430,"430 The Sprawl Mag is a (cyber-)feminist, anti..."
438,Uncharted Magazine,"Fantasy, Horror, Mystery/Crime, Science Fictio...","Flash, Short Story",52 days,Note: we have received several reports of issu...,496,496 Note: we have received several reports of ...